// Title: FoggyWeb Backdoor DLL Loading
// Author: Florian Roth (Nextron Systems)
// Date: 2021-09-27
// Level: critical
// Description: Detects DLL hijacking technique used by NOBELIUM in their FoggyWeb backdoor. Which loads a malicious version of the expected "version.dll" dll
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1587, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceImageLoadEvents
| where FolderPath =~ "C:\\Windows\\ADFS\\version.dll"