// Title: Exchange PowerShell Cmdlet History Deleted
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-26
// Level: high
// Description: Detects the deletion of the Exchange PowerShell cmdlet History logs which may indicate an attempt to destroy forensic evidence
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070
// False Positives:
//   - Possible FP during log rotation

DeviceFileEvents
| where FolderPath contains "_Cmdlet_" and FolderPath startswith "\\Logging\\CmdletInfra\\LocalPowerShell\\Cmdlet\\"