// Title: HackTool - PowerTool Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-11-29
// Level: high
// Description: Detects the execution of the tool PowerTool which has the ability to kill a process, delete its process file, unload drivers, and delete the driver files
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (FolderPath endswith "\\PowerTool.exe" or FolderPath endswith "\\PowerTool64.exe") or ProcessVersionInfoOriginalFileName =~ "PowerTool.exe"