// Title: Potential DLL Sideloading Via JsSchHlp
// Author: frack113
// Date: 2022-12-14
// Level: medium
// Description: Detects potential DLL sideloading using JUSTSYSTEMS Japanese word processor
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001

DeviceImageLoadEvents
| where FolderPath endswith "\\JSESPR.dll" and (not(FolderPath startswith "C:\\Program Files\\Common Files\\Justsystem\\JsSchHlp\\"))