// Title: Renamed Msdt.EXE Execution
// Author: pH-T (Nextron Systems)
// Date: 2022-06-03
// Level: high
// Description: Detects the execution of a renamed "Msdt.exe" binary
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.003
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "msdt.exe" and (not(FolderPath endswith "\\msdt.exe"))