// Title: Suspicious Process Suspension via WERFaultSecure through EDR-Freeze
// Author: Jason (https://github.com/0xbcf)
// Date: 2025-09-23
// Level: high
// Description: Detects attempts to freeze a process likely an EDR or an antimalware service process through EDR-Freeze that abuses the WerFaultSecure.exe process to suspend security software.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - Legitimate usage of WerFaultSecure for debugging purposes

DeviceProcessEvents
| where (ProcessCommandLine contains " /h " and ProcessCommandLine contains " /pid " and ProcessCommandLine contains " /tid " and ProcessCommandLine contains " /encfile " and ProcessCommandLine contains " /cancel " and ProcessCommandLine contains " /type " and ProcessCommandLine contains " 268310") and (FolderPath endswith "\\WerFaultSecure.exe" or ProcessVersionInfoOriginalFileName =~ "WerFaultSecure.exe")