// Title: Suspicious RASdial Activity
// Author: juju4
// Date: 2019-01-16
// Level: medium
// Description: Detects suspicious process related to rasdial.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059
// False Positives:
//   - False positives depend on scripts and administrative tools used in the monitored environment

DeviceProcessEvents
| where FolderPath endswith "rasdial.exe"