// Title: Tamper With Sophos AV Registry Keys
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-02
// Level: high
// Description: Detects tamper attempts to sophos av functionality via registry key modification
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - Some FP may occur when the feature is disabled by the AV itself, you should always investigate if the action was legitimate

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey contains "\\Sophos Endpoint Defense\\TamperProtection\\Config\\SAVEnabled" or RegistryKey contains "\\Sophos Endpoint Defense\\TamperProtection\\Config\\SEDEnabled" or RegistryKey contains "\\Sophos\\SAVService\\TamperProtection\\Enabled")