// Title: Tamper Windows Defender Remove-MpPreference
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-05
// Level: high
// Description: Detects attempts to remove Windows Defender configurations using the 'MpPreference' cmdlet
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - Legitimate PowerShell scripts

DeviceProcessEvents
| where ProcessCommandLine contains "Remove-MpPreference" and (ProcessCommandLine contains "-ControlledFolderAccessProtectedFolders " or ProcessCommandLine contains "-AttackSurfaceReductionRules_Ids " or ProcessCommandLine contains "-AttackSurfaceReductionRules_Actions " or ProcessCommandLine contains "-CheckForSignaturesBeforeRunningScan ")