// Title: Visual Basic Command Line Compiler Usage
// Author: Ensar Şamil, @sblmsrsn, @oscd_initiative
// Date: 2020-10-07
// Level: high
// Description: Detects successful code compilation via Visual Basic Command Line Compiler that utilizes Windows Resource to Object Converter.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027.004
// False Positives:
//   - Utilization of this tool should not be seen in enterprise environment

DeviceProcessEvents
| where FolderPath endswith "\\cvtres.exe" and InitiatingProcessFolderPath endswith "\\vbc.exe"