// Title: WMIC Loading Scripting Libraries
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-10-17
// Level: medium
// Description: Detects threat actors proxy executing code and bypassing application controls by leveraging wmic and the `/FORMAT` argument switch to download and execute an XSL file (i.e js, vbs, etc).
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1220
// False Positives:
//   - The command wmic os get lastboottuptime loads vbscript.dll
//   - The command wmic os get locale loads vbscript.dll
//   - Since the ImageLoad event doesn't have enough information in this case. It's better to look at the recent process creation events that spawned the WMIC process and investigate the command line and parent/child processes to get more insights

DeviceImageLoadEvents
| where (FolderPath endswith "\\jscript.dll" or FolderPath endswith "\\vbscript.dll") and InitiatingProcessFolderPath endswith "\\wmic.exe"