// Title: Potential Russian APT Credential Theft Activity
// Author: Florian Roth (Nextron Systems)
// Date: 2019-02-21
// Level: critical
// Description: Detects Russian group activity as described in Global Threat Report 2019 by Crowdstrike
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.001, attack.t1003.003, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "adexplorer -snapshot \"\" c:\\users\\" and ProcessCommandLine contains "\\downloads\\" and ProcessCommandLine contains ".snp") or (ProcessCommandLine contains "xcopy /S /E /C /Q /H \\\\" and ProcessCommandLine contains "\\sysvol\\")