// Title: Curl Usage on Linux
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Level: low
// Description: Detects a curl process start on linux, which indicates a file download from a remote location or a simple web request to a remote server
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// False Positives:
//   - Scripts created by developers and admins
//   - Administrative activity

DeviceProcessEvents
| where FolderPath endswith "/curl"