// Title: DD File Overwrite
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research), MSTIC
// Date: 2021-10-15
// Level: low
// Description: Detects potential overwriting and deletion of a file using DD.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1485
// False Positives:
//   - Any user deleting files that way.

DeviceProcessEvents
| where (FolderPath in~ ("/bin/dd", "/usr/bin/dd")) and ProcessCommandLine contains "of=" and (ProcessCommandLine contains "if=/dev/zero" or ProcessCommandLine contains "if=/dev/null")