// Title: Code Execution via Pcwutl.dll
// Author: Julia Fomina, oscd.community
// Date: 2020-10-05
// Level: medium
// Description: Detects launch of executable by calling the LaunchApplication function from pcwutl.dll library.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011
// False Positives:
//   - Use of Program Compatibility Troubleshooter Helper

DeviceProcessEvents
| where (ProcessCommandLine contains "pcwutl" and ProcessCommandLine contains "LaunchApplication") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")