// Title: Firewall Rule Deleted Via Netsh.EXE
// Author: frack113
// Date: 2022-08-14
// Level: medium
// Description: Detects the removal of a port or application rule in the Windows Firewall configuration using netsh
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004
// False Positives:
//   - Legitimate administration activity
//   - Software installations and removal

DeviceProcessEvents
| where ((ProcessCommandLine contains "firewall" and ProcessCommandLine contains "delete ") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")) and (not(((ProcessCommandLine contains "advfirewall firewall delete rule name=\"Avast Antivirus Admin Client\"" and InitiatingProcessFolderPath endswith "\\instup.exe") or (ProcessCommandLine contains "name=Dropbox" and InitiatingProcessFolderPath endswith "\\Dropbox.exe"))))