// Title: HackTool - Hydra Password Bruteforce Execution
// Author: Vasiliy Burov
// Date: 2020-10-05
// Level: high
// Description: Detects command line parameters used by Hydra password guessing hack tool
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1110, attack.t1110.001
// False Positives:
//   - Software that uses the caret encased keywords PASS and USER in its command line

DeviceProcessEvents
| where (ProcessCommandLine contains "^USER^" or ProcessCommandLine contains "^PASS^") and (ProcessCommandLine contains "-u " and ProcessCommandLine contains "-p ")