// Title: PktMon.EXE Execution
// Author: frack113
// Date: 2022-03-17
// Level: medium
// Description: Detects execution of PktMon, a tool that captures network packets.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.credential-access, attack.t1040
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where FolderPath endswith "\\pktmon.exe" or ProcessVersionInfoOriginalFileName =~ "PktMon.exe"