// Title: Psexec Execution
// Author: omkar72
// Date: 2020-10-30
// Level: medium
// Description: Detects user accept agreement execution in psexec commandline
// MITRE Tactic: Execution
// Tags: attack.execution, attack.lateral-movement, attack.t1569, attack.t1021
// False Positives:
//   - Administrative scripts.

DeviceProcessEvents
| where FolderPath endswith "\\psexec.exe" or ProcessVersionInfoOriginalFileName =~ "psexec.c"