// Title: Renamed Sysinternals Sdelete Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-09-06
// Level: high
// Description: Detects the use of a renamed SysInternals Sdelete, which is something an administrator shouldn't do (the renaming)
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1485
// False Positives:
//   - System administrator usage

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "sdelete.exe" and (not((FolderPath endswith "\\sdelete.exe" or FolderPath endswith "\\sdelete64.exe")))