// Title: Verclsid.exe Runs COM Object
// Author: Victor Sergeev, oscd.community
// Date: 2020-10-09
// Level: medium
// Description: Detects when verclsid.exe is used to run COM object via GUID
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218

DeviceProcessEvents
| where ((ProcessCommandLine contains "/S" and ProcessCommandLine contains "/C") and (FolderPath endswith "\\verclsid.exe" or ProcessVersionInfoOriginalFileName =~ "verclsid.exe")) and (not(((ProcessCommandLine contains "verclsid.exe\" /S /C {" and ProcessCommandLine contains "} /I {") and InitiatingProcessFolderPath endswith "C:\\Windows\\System32\\RuntimeBroker.exe")))