// Title: Elise Backdoor Activity
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2018-01-31
// Level: critical
// Description: Detects Elise backdoor activity used by APT32
// MITRE Tactic: Execution
// Tags: attack.g0030, attack.g0050, attack.s0081, attack.execution, attack.t1059.003, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ((ProcessCommandLine contains "\\Windows\\Caches\\NavShExt.dll" and ProcessCommandLine contains "/c del") or FolderPath endswith "\\Microsoft\\Network\\svchost.exe") or (ProcessCommandLine contains ",Setting" and (ProcessCommandLine endswith "\\AppData\\Roaming\\MICROS~1\\Windows\\Caches\\NavShExt.dll" or ProcessCommandLine endswith "\\AppData\\Roaming\\Microsoft\\Windows\\Caches\\NavShExt.dll"))