// Title: Emotet Loader Execution Via .LNK File
// Author: @kostastsale
// Date: 2022-04-22
// Level: high
// Description: Detects the Emotet Epoch4 loader as reported by @malware_traffic back in 2022.
// The ".lnk" file was delivered via phishing campaign.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.006, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "findstr" and ProcessCommandLine contains ".vbs" and ProcessCommandLine contains ".lnk") and (FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe") and (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\explorer.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe")