// Title: Goofy Guineapig Backdoor IOC
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-14
// Level: high
// Description: Detects malicious indicators seen used by the Goofy Guineapig malware
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath in~ ("C:\\ProgramData\\GoogleUpdate\\config.dat", "C:\\ProgramData\\GoogleUpdate\\GoogleUpdate.exe", "C:\\ProgramData\\GoogleUpdate\\GoogleUpdate\\tmp.bat", "C:\\ProgramData\\GoogleUpdate\\goopdate.dll")