// Title: UNC4841 - Potential SEASPY Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-16
// Level: critical
// Description: Detects execution of specific named binaries which were used by UNC4841 to deploy their SEASPY backdoor
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "/BarracudaMailService" or FolderPath endswith "/resize2fstab" or FolderPath endswith "/resize_reisertab"