// Title: UNC4841 - Email Exfiltration File Pattern
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-16
// Level: high
// Description: Detects filename pattern of email related data used by UNC4841 for staging and exfiltration
// MITRE Tactic: Execution
// Tags: attack.execution, attack.persistence, attack.defense-evasion, detection.emerging-threats

DeviceFileEvents
| where FolderPath matches regex "/mail/tmp/[a-zA-Z0-9]{3}[0-9]{3}\\.tar\\.gz"