// Title: New Outlook Macro Created
// Author: @ScoubiMtl
// Date: 2021-04-05
// Level: medium
// Description: Detects the creation of a macro file for Outlook.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.command-and-control, attack.t1137, attack.t1008, attack.t1546
// False Positives:
//   - User genuinely creates a VB Macro for their email

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\outlook.exe" and FolderPath endswith "\\Microsoft\\Outlook\\VbaProject.OTM"