// Title: APT29 2018 Phishing Campaign File Indicators
// Author: @41thexplorer
// Date: 2018-11-20
// Level: critical
// Description: Detects indicators of APT 29 (Cozy Bear) phishing-campaign as reported by mandiant
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath contains "ds7002.lnk" or FolderPath contains "ds7002.pdf" or FolderPath contains "ds7002.zip"