// Title: Screen Capture - macOS
// Author: remotephone, oscd.community
// Date: 2020-10-13
// Level: low
// Description: Detects attempts to use screencapture to collect macOS screenshots
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1113
// False Positives:
//   - Legitimate user activity taking screenshots

DeviceProcessEvents
| where FolderPath =~ "/usr/sbin/screencapture"