// Title: COLDSTEEL RAT Service Persistence Execution
// Author: X__Junior (Nextron Systems)
// Date: 2023-04-30
// Level: critical
// Description: Detects the creation of an "svchost" process with specific command line flags, that were seen present and used by ColdSteel RAT
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine endswith " -k msupdate" or ProcessCommandLine endswith " -k msupdate2" or ProcessCommandLine endswith " -k alg") and FolderPath endswith "\\svchost.exe"