// Title: Potential COLDSTEEL Persistence Service DLL Load
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-02
// Level: high
// Description: Detects a suspicious DLL load by an "svchost" process based on location and name that might be related to ColdSteel RAT. This DLL location and name has been seen used by ColdSteel as the service DLL for its persistence mechanism
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceImageLoadEvents
| where FolderPath endswith "\\AppData\\Roaming\\newdev.dll" and InitiatingProcessFolderPath endswith "\\svchost.exe"