// Title: Suspicious PrinterPorts Creation (CVE-2020-1048)
// Author: EagleEye Team, Florian Roth
// Date: 2020-05-13
// Level: high
// Description: Detects new commands that add new printer port which point to suspicious file
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.execution, attack.t1059.001, cve.2020-1048, detection.emerging-threats
// False Positives:
//   - New printer port install on host

DeviceProcessEvents
| where (ProcessCommandLine contains "Add-PrinterPort -Name" and (ProcessCommandLine contains ".exe" or ProcessCommandLine contains ".dll" or ProcessCommandLine contains ".bat")) or ProcessCommandLine contains "Generic / Text Only"