// Title: Cab File Extraction Via Wusa.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-04
// Level: medium
// Description: Detects execution of the "wusa.exe" (Windows Update Standalone Installer) utility to extract cab using the "/extract" argument that is no longer supported.
// MITRE Tactic: Execution
// Tags: attack.execution, detection.threat-hunting
// False Positives:
//   - The "extract" flag still works on older 'wusa.exe' versions, which could be a legitimate use (monitor the path of the cab being extracted)

DeviceProcessEvents
| where ProcessCommandLine contains "/extract:" and FolderPath endswith "\\wusa.exe"