// Title: Microsoft Excel Add-In Loaded
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-12
// Level: low
// Description: Detects Microsoft Excel loading an Add-In (.xll) file
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.002, detection.threat-hunting
// False Positives:
//   - The rules is only looking for ".xll" loads. So some false positives are expected with legitimate and allowed XLLs

DeviceImageLoadEvents
| where FolderPath endswith ".xll" and InitiatingProcessFolderPath endswith "\\excel.exe"