// Title: Crontab Enumeration
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: low
// Description: Detects usage of crontab to list the tasks of the user
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1007
// False Positives:
//   - Legitimate use of crontab

DeviceProcessEvents
| where ProcessCommandLine contains " -l" and FolderPath endswith "/crontab"