// Title: Potential Container Discovery Via Inodes Listing
// Author: Seth Hanford
// Date: 2023-08-23
// Level: low
// Description: Detects listing of the inodes of the "/" directory to determine if the we are running inside of a container.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1082
// False Positives:
//   - Legitimate system administrator usage of these commands
//   - Some container tools or deployments may use these techniques natively to determine how they proceed with execution, and will need to be filtered

DeviceProcessEvents
| where ((ProcessCommandLine contains " -" and ProcessCommandLine contains "i") and (ProcessCommandLine contains " -" and ProcessCommandLine contains "d")) and ProcessCommandLine endswith " /" and FolderPath endswith "/ls"