// Title: HackTool - Mimikatz Kirbi File Creation
// Author: Florian Roth (Nextron Systems), David ANDRE
// Date: 2021-11-08
// Level: critical
// Description: Detects the creation of files created by mimikatz such as ".kirbi", "mimilsa.log", etc.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1558
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith ".kirbi" or FolderPath endswith "mimilsa.log"