// Title: Advanced IP Scanner - File Event
// Author: @ROxPinTeddy
// Date: 2020-05-12
// Level: medium
// Description: Detects the use of Advanced IP Scanner. Seems to be a popular tool for ransomware groups.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1046
// False Positives:
//   - Legitimate administrative use

DeviceFileEvents
| where FolderPath contains "\\AppData\\Local\\Temp\\Advanced IP Scanner 2"