// Title: Potential CSharp Streamer RAT Loading .NET Executable Image
// Author: Luca Di Bartolomeo
// Date: 2024-06-22
// Level: high
// Description: Detects potential CSharp Streamer RAT loading .NET executable image by using the default file name and path associated with the tool.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002, detection.emerging-threats

DeviceImageLoadEvents
| where FolderPath matches regex "\\\\AppData\\\\Local\\\\Temp\\\\dat[0-9A-Z]{4}\\.tmp"