// Title: Dumping Process via Sqldumper.exe
// Author: Kirill Kiryanov, oscd.community
// Date: 2020-10-08
// Level: medium
// Description: Detects process dump via legitimate sqldumper.exe binary
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.001
// False Positives:
//   - Legitimate MSSQL Server actions

DeviceProcessEvents
| where (ProcessCommandLine contains "0x0110" or ProcessCommandLine contains "0x01100:40") and FolderPath endswith "\\sqldumper.exe"