// Title: HackTool - SecurityXploded Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2018-12-19
// Level: critical
// Description: Detects the execution of SecurityXploded Tools
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1555
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessVersionInfoCompanyName =~ "SecurityXploded" or FolderPath endswith "PasswordDump.exe" or ProcessVersionInfoOriginalFileName endswith "PasswordDump.exe"