// Title: Potential PowerShell Console History Access Attempt via History File
// Author: Luc Génaux
// Date: 2025-04-03
// Level: medium
// Description: Detects potential access attempts to the PowerShell console history directly via history file (ConsoleHost_history.txt).
// This can give access to plaintext passwords used in PowerShell commands or used for general reconnaissance.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.001
// False Positives:
//   - Legitimate access of the console history file is possible

DeviceProcessEvents
| where ProcessCommandLine contains "ConsoleHost_history.txt" or ProcessCommandLine contains "(Get-PSReadLineOption).HistorySavePath"