// Title: FileFix - Suspicious Child Process from Browser File Upload Abuse
// Author: 0xFustang
// Date: 2025-06-26
// Level: high
// Description: Detects potentially suspicious subprocesses such as LOLBINs spawned by web browsers. This activity could be associated with the "FileFix" social engineering technique,
// where users are tricked into launching the file explorer via a browser-based phishing page and pasting malicious commands into the address bar.
// The technique abuses clipboard manipulation and disguises command execution as benign file path access, resulting in covert execution of system utilities.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.004
// False Positives:
//   - Legitimate use of PowerShell or other utilities launched from browser extensions or automation tools

DeviceProcessEvents
| where ProcessCommandLine contains "#" and (FolderPath endswith "\\bitsadmin.exe" or FolderPath endswith "\\certutil.exe" or FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe") and (InitiatingProcessFolderPath endswith "\\brave.exe" or InitiatingProcessFolderPath endswith "\\chrome.exe" or InitiatingProcessFolderPath endswith "\\firefox.exe" or InitiatingProcessFolderPath endswith "\\msedge.exe")