// Title: Insecure Proxy/DOH Transfer Via Curl.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-27
// Level: medium
// Description: Detects execution of "curl.exe" with the "insecure" flag over proxy or DOH.
// MITRE Tactic: Execution
// Tags: attack.execution
// False Positives:
//   - Access to badly maintained internal or development systems

DeviceProcessEvents
| where (ProcessCommandLine contains "--doh-insecure" or ProcessCommandLine contains "--proxy-insecure") and (FolderPath endswith "\\curl.exe" or ProcessVersionInfoOriginalFileName =~ "curl.exe")