// Title: Network Connection Initiated By Eqnedt32.EXE
// Author: Max Altgelt (Nextron Systems)
// Date: 2022-04-14
// Level: high
// Description: Detects network connections from the Equation Editor process "eqnedt32.exe".
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1203
// False Positives:
//   - Unlikely

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\eqnedt32.exe"