// Title: PowerShell Script Execution Policy Enabled
// Author: Nasreddine Bencherchali (Nextron Systems), Thurein Oo
// Date: 2023-10-18
// Level: low
// Description: Detects the enabling of the PowerShell script execution policy. Once enabled, this policy allows scripts to be executed.
// MITRE Tactic: Execution
// Tags: attack.execution
// False Positives:
//   - Likely

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\Policies\\Microsoft\\Windows\\PowerShell\\EnableScripts"