// Title: WMIC Remote Command Execution
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-14
// Level: medium
// Description: Detects the execution of WMIC to query information on a remote system
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047

DeviceProcessEvents
| where ((ProcessCommandLine contains "-node:" or ProcessCommandLine contains "/node:" or ProcessCommandLine contains "–node:" or ProcessCommandLine contains "—node:" or ProcessCommandLine contains "―node:") and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")) and (not((ProcessCommandLine contains "localhost" or ProcessCommandLine contains "127.0.0.1")))