// Title: Adwind RAT / JRAT
// Author: Florian Roth (Nextron Systems), Tom Ueltschi, Jonhnathan Ribeiro, oscd.community
// Date: 2017-11-10
// Level: high
// Description: Detects javaw.exe in AppData folder as used by Adwind / JRAT
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.005, attack.t1059.007, detection.emerging-threats

DeviceProcessEvents
| where (ProcessCommandLine contains "\\AppData\\Roaming\\Oracle" and ProcessCommandLine contains "\\java" and ProcessCommandLine contains ".exe ") or (ProcessCommandLine contains "cscript.exe" and ProcessCommandLine contains "Retrive" and ProcessCommandLine contains ".vbs ")