// Title: Diamond Sleet APT Process Activity Indicators
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-24
// Level: high
// Description: Detects process creation activity indicators related to Diamond Sleet APT
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains " uTYNkfKxHiZrx3KJ"