// Title: File Creation Related To RAT Clients
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-12-19
// Level: high
// Description: File .conf created related to VenomRAT, AsyncRAT and Lummac samples observed in the wild.
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// False Positives:
//   - Legitimate software creating a file with the same name

DeviceFileEvents
| where FolderPath contains "\\AppData\\Roaming\\" and ((FolderPath contains "\\mydata\\" or FolderPath contains "\\datalogs\\" or FolderPath contains "\\hvnc\\" or FolderPath contains "\\dcrat\\") and (FolderPath endswith "\\datalogs.conf" or FolderPath endswith "\\hvnc.conf" or FolderPath endswith "\\dcrat.conf"))