// Title: Fireball Archer Install
// Author: Florian Roth (Nextron Systems)
// Date: 2017-06-03
// Level: high
// Description: Detects Archer malware invocation via rundll32
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1218.011, detection.emerging-threats

DeviceProcessEvents
| where ProcessCommandLine contains "rundll32.exe" and ProcessCommandLine contains "InstallArcherSvc"