// Title: Lace Tempest Cobalt Strike Download
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-11-09
// Level: high
// Description: Detects specific command line execution used by Lace Tempest to download Cobalt Strike as reported by SysAid Team
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "-nop -w hidden -c IEX ((new-object net.webclient).downloadstring(" and ProcessCommandLine contains "/a')"