// Title: Potential Goofy Guineapig Backdoor Activity
// Author: X__Junior (Nextron Systems)
// Date: 2023-05-14
// Level: high
// Description: Detects a specific broken command that was used by Goofy-Guineapig as described by the NCSC report.
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "choice /t %d /d y /n >nul"