// Title: Potential APT FIN7 Related PowerShell Script Created
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-04
// Level: high
// Description: Detects PowerShell script file creation with specific name or suffix which was seen being used often by FIN7 PowerShell scripts
// MITRE Tactic: Execution
// Tags: attack.execution, attack.g0046, detection.emerging-threats

DeviceFileEvents
| where FolderPath in~ ("host_ip.ps1") or FolderPath endswith "_64refl.ps1"