// Title: Ursnif Redirection Of Discovery Commands
// Author: @kostastsale
// Date: 2023-07-16
// Level: high
// Description: Detects the redirection of Ursnif discovery commands as part of the initial execution of the malware.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "/C " and (ProcessCommandLine contains " >> " and ProcessCommandLine contains "\\AppData\\local\\temp*.bin")) and FolderPath endswith "\\cmd.exe" and InitiatingProcessFolderPath endswith "\\explorer.exe"