// Title: Disable Privacy Settings Experience in Registry
// Author: frack113
// Date: 2022-10-02
// Level: medium
// Description: Detects registry modifications that disable Privacy Settings Experience
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - Legitimate admin script

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\SOFTWARE\\Policies\\Microsoft\\Windows\\OOBE\\DisablePrivacyExperience"