// Title: Kapeka Backdoor Configuration Persistence
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-07-03
// Level: medium
// Description: Detects registry set activity of a value called "Seed" stored in the "\Cryptography\Providers\" registry key.
// The Kapeka backdoor leverages this location to register a new SIP provider for backdoor configuration persistence.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1553.003, detection.emerging-threats

DeviceRegistryEvents
| where (RegistryKey contains "\\SOFTWARE\\Microsoft\\Cryptography\\Providers\\{" and RegistryKey endswith "\\Seed") and (not(RegistryValueData contains "(Empty)"))