// Title: Potential COLDSTEEL RAT Windows User Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-02
// Level: high
// Description: Detects creation of a new user profile with a specific username, seen being used by some variants of the COLDSTEEL RAT.
// MITRE Tactic: Persistence
// Tags: attack.persistence, detection.emerging-threats

DeviceRegistryEvents
| where (RegistryValueData contains "ANONYMOUS" or RegistryValueData contains "_DomainUser_") and (RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\ProfileList\\S-1-5-21-" and RegistryKey contains "\\ProfileImagePath")