// Title: Potential COLDSTEEL RAT File Indicators
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-30
// Level: high
// Description: Detects the creation of a file named "dllhost.exe" in the "C:\users\public\Documents\" directory. Seen being used by the COLDSTEEL RAT in some of its variants.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, detection.emerging-threats

DeviceFileEvents
| where FolderPath =~ "C:\\users\\public\\Documents\\dllhost.exe"