// Title: FTP Connection Open Attempt Via Winscp CLI
// Author: frack113
// Date: 2025-10-12
// Level: medium
// Description: Detects the execution of Winscp with the "-command" and the "open" flags in order to open an FTP connection. Akira ransomware was seen using this technique in order to exfiltrate data.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1048, detection.threat-hunting

DeviceProcessEvents
| where ((ProcessCommandLine contains "open " and ProcessCommandLine contains "ftp://") and (ProcessCommandLine contains "-command" or ProcessCommandLine contains "/command" or ProcessCommandLine contains "–command" or ProcessCommandLine contains "—command" or ProcessCommandLine contains "―command")) and (FolderPath endswith "\\WinSCP.exe" or ProcessVersionInfoOriginalFileName =~ "winscp.exe")