// Title: Potential Persistence Via AppCompat RegisterAppRestart Layer
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-01-01
// Level: medium
// Description: Detects the setting of the REGISTERAPPRESTART compatibility layer on an application.
// This compatibility layer allows an application to register for restart using the "RegisterApplicationRestart" API.
// This can be potentially abused as a persistence mechanism.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.011
// False Positives:
//   - Legitimate applications making use of this feature for compatibility reasons

DeviceRegistryEvents
| where RegistryValueData contains "REGISTERAPPRESTART" and RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Layers*"