// Title: Potential Execution of Sysinternals Tools
// Author: Markus Neis
// Date: 2017-08-28
// Level: low
// Description: Detects command lines that contain the 'accepteula' flag which could be a sign of execution of one of the Sysinternals tools
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1588.002
// False Positives:
//   - Legitimate use of SysInternals tools
//   - Programs that use the same command line flag

DeviceProcessEvents
| where ProcessCommandLine contains " -accepteula" or ProcessCommandLine contains " /accepteula" or ProcessCommandLine contains " –accepteula" or ProcessCommandLine contains " —accepteula" or ProcessCommandLine contains " ―accepteula"