// Title: PUA - Sysinternal Tool Execution - Registry
// Author: Markus Neis
// Date: 2017-08-28
// Level: low
// Description: Detects the execution of a Sysinternals Tool via the creation of the "accepteula" registry key
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1588.002
// False Positives:
//   - Legitimate use of SysInternals tools
//   - Programs that use the same Registry Key

DeviceRegistryEvents
| where ActionType =~ "RegistryKeyCreated" and RegistryKey endswith "\\EulaAccepted"