// Title: Conti NTDS Exfiltration Command
// Author: Max Altgelt (Nextron Systems), Tobias Michalski (Nextron Systems)
// Date: 2021-08-09
// Level: high
// Description: Detects a command used by conti to exfiltrate NTDS
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1560, detection.emerging-threats

DeviceProcessEvents
| where ProcessCommandLine contains "7za.exe" and ProcessCommandLine contains "\\C$\\temp\\log.zip"