// Title: New Custom Shim Database Created
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-29
// Level: medium
// Description: Adversaries may establish persistence and/or elevate privileges by executing malicious content triggered by application shims.
// The Microsoft Windows Application Compatibility Infrastructure/Framework (Application Shim) was created to allow for backward compatibility of software as the operating system codebase changes over time.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.009
// False Positives:
//   - Legitimate custom SHIM installations will also trigger this rule

DeviceFileEvents
| where FolderPath contains ":\\Windows\\apppatch\\Custom\\" or FolderPath contains ":\\Windows\\apppatch\\CustomSDB\\"