// Title: Potential COM Object Hijacking Via TreatAs Subkey - Registry
// Author: Kutepov Anton, oscd.community
// Date: 2019-10-23
// Level: medium
// Description: Detects COM object hijacking via TreatAs subkey
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.015
// False Positives:
//   - Maybe some system utilities in rare cases use linking keys for backward compatibility

DeviceRegistryEvents
| where (ActionType =~ "RegistryKeyCreated" and (RegistryKey endswith "HKU*" and RegistryKey endswith "Classes\\CLSID*" and RegistryKey contains "\\TreatAs")) and (not(InitiatingProcessFolderPath =~ "C:\\WINDOWS\\system32\\svchost.exe"))