// Title: Triple Cross eBPF Rootkit Default Persistence
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-05
// Level: high
// Description: Detects the creation of "ebpfbackdoor" files in both "cron.d" and "sudoers.d" directories. Which both are related to the TripleCross persistence method
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.defense-evasion, attack.t1053.003
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith "ebpfbackdoor"