// Title: User Added to Local Administrators Group
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-12
// Level: medium
// Description: Detects addition of users to the local administrator group via "Net" or "Add-LocalGroupMember".
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1098
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where (ProcessCommandLine contains " administrators " or ProcessCommandLine contains " administrateur") and ((ProcessCommandLine contains "localgroup " and ProcessCommandLine contains " /add") or (ProcessCommandLine contains "Add-LocalGroupMember " and ProcessCommandLine contains " -Group "))