// Title: WMI Persistence - Script Event Consumer File Write
// Author: Thomas Patzke
// Date: 2018-03-07
// Level: high
// Description: Detects file writes of WMI script event consumer
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.t1546.003, attack.persistence
// False Positives:
//   - Dell Power Manager (C:\Program Files\Dell\PowerManager\DpmPowerPlanSetup.exe)

DeviceFileEvents
| where InitiatingProcessFolderPath =~ "C:\\WINDOWS\\system32\\wbem\\scrcons.exe"