// Title: APT29 2018 Phishing Campaign CommandLine Indicators
// Author: Florian Roth (Nextron Systems), @41thexplorer
// Date: 2018-11-20
// Level: critical
// Description: Detects indicators of APT 29 (Cozy Bear) phishing-campaign as reported by mandiant
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218.011, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "-noni -ep bypass $" or (ProcessCommandLine contains "cyzfc.dat," and ProcessCommandLine contains "PointFunctionCall")