// Title: Qakbot Regsvr32 Calc Pattern
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-26
// Level: high
// Description: Detects a specific command line of "regsvr32" where the "calc" keyword is used in conjunction with the "/s" flag. This behavior is often seen used by Qakbot
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains " -s" or ProcessCommandLine contains " /s" or ProcessCommandLine contains " –s" or ProcessCommandLine contains " —s" or ProcessCommandLine contains " ―s") and ProcessCommandLine endswith " calc" and FolderPath endswith "\\regsvr32.exe"