// Title: Pingback Backdoor File Indicators
// Author: Bhabesh Raj
// Date: 2021-05-05
// Level: high
// Description: Detects the use of Pingback backdoor that creates ICMP tunnel for C2 as described in the trustwave report
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.persistence, attack.t1574.001, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "updata.exe" and FolderPath =~ "C:\\Windows\\oci.dll"