// Title: Suspicious VBScript UN2452 Pattern
// Author: Florian Roth (Nextron Systems)
// Date: 2021-03-05
// Level: high
// Description: Detects suspicious inline VBScript keywords as used by UNC2452
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001, detection.emerging-threats

DeviceProcessEvents
| where (ProcessCommandLine contains "Execute" and ProcessCommandLine contains "CreateObject" and ProcessCommandLine contains "RegRead" and ProcessCommandLine contains "window.close" and ProcessCommandLine contains "\\Microsoft\\Windows\\CurrentVersion") and (not(ProcessCommandLine contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"))