// Title: Suspicious Userinit Child Process
// Author: Florian Roth (Nextron Systems), Samir Bousseaden (idea)
// Date: 2019-06-17
// Level: medium
// Description: Detects a suspicious child process of userinit
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1055
// False Positives:
//   - Administrative scripts

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\userinit.exe" and (not(((FolderPath endswith "\\explorer.exe" or ProcessVersionInfoOriginalFileName =~ "explorer.exe" or ProcessCommandLine =~ "C:\\Windows\\Explorer.EXE") or ProcessCommandLine contains "\\netlogon\\" or isnull(FolderPath))))