// Title: Use of Remote.exe
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-02
// Level: medium
// Description: Remote.exe is part of WinDbg in the Windows SDK and can be used for AWL bypass and running remote files.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1127
// False Positives:
//   - Approved installs of Windows SDK with Debugging Tools for Windows (WinDbg).

DeviceProcessEvents
| where FolderPath endswith "\\remote.exe" or ProcessVersionInfoOriginalFileName =~ "remote.exe"