// Title: VolumeShadowCopy Symlink Creation Via Mklink
// Author: Teymur Kheirkhabarov, oscd.community
// Date: 2019-10-22
// Level: high
// Description: Shadow Copies storage symbolic link creation using operating systems utilities
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.002, attack.t1003.003
// False Positives:
//   - Legitimate administrator working with shadow copies, access for backup purposes

DeviceProcessEvents
| where ProcessCommandLine contains "mklink" and ProcessCommandLine contains "HarddiskVolumeShadowCopy"