// Title: FunkLocker Ransomware File Creation
// Author: Saiprashanth Pulisetti ( @Prashanthblogs)
// Date: 2025-08-08
// Level: high
// Description: Detects the creation of files with the ".funksec" extension, which is appended to encrypted files by the FunkLocker ransomware.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1486, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith ".funksec"