// Title: LockerGoga Ransomware Activity
// Author: Vasiliy Burov, oscd.community
// Date: 2020-10-18
// Level: critical
// Description: Detects LockerGoga ransomware activity via specific command line.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1486, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "-i SM-tgytutrc -s"