// Title: Potential Dtrack RAT Activity
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-10-30
// Level: critical
// Description: Detects potential Dtrack RAT activity via specific process patterns
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1490, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "\\temp\\res.ip" and ProcessCommandLine matches regex "ipconfig\\s+/all") or (ProcessCommandLine contains "interface ip show config" and ProcessCommandLine contains "\\temp\\netsh.res") or ProcessCommandLine matches regex "ping\\s+-n.{6,64}echo EEEE\\s?>\\s?"