// Title: Diamond Sleet APT File Creation Indicators
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-24
// Level: high
// Description: Detects file creation activity that is related to Diamond Sleet APT activity
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith ":\\ProgramData\\4800-84DC-063A6A41C5C" or FolderPath endswith ":\\ProgramData\\clip.exe" or FolderPath endswith ":\\ProgramData\\DSROLE.dll" or FolderPath endswith ":\\ProgramData\\Forest64.exe" or FolderPath endswith ":\\ProgramData\\readme.md" or FolderPath endswith ":\\ProgramData\\Version.dll" or FolderPath endswith ":\\ProgramData\\wsmprovhost.exe"