// Title: PUA - NirCmd Execution As LOCAL SYSTEM
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-24
// Level: high
// Description: Detects the use of NirCmd tool for command execution as SYSTEM user
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1569.002, attack.s0029
// False Positives:
//   - Legitimate use by administrators

DeviceProcessEvents
| where ProcessCommandLine contains " runassystem "