// Title: Renamed PsExec Service Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-21
// Level: high
// Description: Detects suspicious launch of a renamed version of the PSEXESVC service with, which is not often used by legitimate administrators
// MITRE Tactic: Execution
// Tags: attack.execution
// False Positives:
//   - Legitimate administrative tasks

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "psexesvc.exe" and (not(FolderPath =~ "C:\\Windows\\PSEXESVC.exe"))