// Title: CMSTP Execution Process Creation
// Author: Nik Seetharaman
// Date: 2018-07-16
// Level: high
// Description: Detects various indicators of Microsoft Connection Manager Profile Installer execution
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218.003, attack.g0069, car.2019-04-001
// False Positives:
//   - Legitimate CMSTP use (unlikely in modern enterprise environments)

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\cmstp.exe"