// Title: HackTool - Wmiexec Default Powershell Command
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-08
// Level: high
// Description: Detects the execution of PowerShell with a specific flag sequence that is used by the Wmiexec script
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.lateral-movement
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "-NoP -NoL -sta -NonI -W Hidden -Exec Bypass -Enc"