// Title: Outgoing Logon with New Credentials
// Author: Max Altgelt (Nextron Systems)
// Date: 2022-04-06
// Level: low
// Description: Detects logon events that specify new credentials
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.lateral-movement, attack.t1550
// False Positives:
//   - Legitimate remote administration activity

DeviceLogonEvents
| where LogonType == 9