// Title: Potential CCleanerReactivator.DLL Sideloading
// Author: X__Junior
// Date: 2023-07-13
// Level: medium
// Description: Detects potential DLL sideloading of "CCleanerReactivator.dll"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001
// False Positives:
//   - False positives could occur from other custom installation paths. Apply additional filters accordingly.

DeviceImageLoadEvents
| where FolderPath endswith "\\CCleanerReactivator.dll" and (not((InitiatingProcessFolderPath endswith "\\CCleanerReactivator.exe" and (InitiatingProcessFolderPath startswith "C:\\Program Files\\CCleaner\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\CCleaner\\"))))