// Title: Process Launched Without Image Name
// Author: Matt Anderson (Huntress)
// Date: 2024-07-23
// Level: medium
// Description: Detect the use of processes with no name (".exe"), which can be used to evade Image-based detections.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// False Positives:
//   - Rare legitimate software.

DeviceProcessEvents
| where FolderPath endswith "\\.exe"