// Title: Renamed MegaSync Execution
// Author: Sittikorn S
// Date: 2021-06-22
// Level: high
// Description: Detects the execution of a renamed MegaSync.exe as seen used by ransomware families like Nefilim, Sodinokibi, Pysa, and Conti.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// False Positives:
//   - Software that illegally integrates MegaSync in a renamed form
//   - Administrators that have renamed MegaSync

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "megasync.exe" and (not(FolderPath endswith "\\megasync.exe"))