// Title: XSL Script Execution Via WMIC.EXE
// Author: Timur Zinniatullin, oscd.community, Swachchhanda Shrawan Poudel
// Date: 2019-10-21
// Level: medium
// Description: Detects the execution of WMIC with the "format" flag to potentially load XSL files.
// Adversaries abuse this functionality to execute arbitrary files while potentially bypassing application whitelisting defenses.
// Extensible Stylesheet Language (XSL) files are commonly used to describe the processing and rendering of data within XML files.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1220
// False Positives:
//   - WMIC.exe FP depend on scripts and administrative methods used in the monitored environment.
//   - Static format arguments - https://petri.com/command-line-wmi-part-3

DeviceProcessEvents
| where ((ProcessCommandLine contains "-format" or ProcessCommandLine contains "/format" or ProcessCommandLine contains "–format" or ProcessCommandLine contains "—format" or ProcessCommandLine contains "―format") and FolderPath endswith "\\wmic.exe") and (not((ProcessCommandLine contains "Format:List" or ProcessCommandLine contains "Format:htable" or ProcessCommandLine contains "Format:hform" or ProcessCommandLine contains "Format:table" or ProcessCommandLine contains "Format:mof" or ProcessCommandLine contains "Format:value" or ProcessCommandLine contains "Format:rawxml" or ProcessCommandLine contains "Format:xml" or ProcessCommandLine contains "Format:csv")))