// Title: Exports Registry Key To a File
// Author: Oddvar Moe, Sander Wiebing, oscd.community
// Date: 2020-10-07
// Level: low
// Description: Detects the export of the target Registry key to a file.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.discovery, attack.t1012
// False Positives:
//   - Legitimate export of keys

DeviceProcessEvents
| where ((ProcessCommandLine contains " -E " or ProcessCommandLine contains " /E " or ProcessCommandLine contains " –E " or ProcessCommandLine contains " —E " or ProcessCommandLine contains " ―E ") and (FolderPath endswith "\\regedit.exe" or ProcessVersionInfoOriginalFileName =~ "REGEDIT.EXE")) and (not(((ProcessCommandLine contains "hklm" or ProcessCommandLine contains "hkey_local_machine") and (ProcessCommandLine endswith "\\system" or ProcessCommandLine endswith "\\sam" or ProcessCommandLine endswith "\\security"))))