// Title: Network Connection Initiated To DevTunnels Domain
// Author: Kamran Saifullah
// Date: 2023-11-20
// Level: medium
// Description: Detects network connections to Devtunnels domains initiated by a process on a system. Attackers can abuse that feature to establish a reverse shell or persistence on a machine.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567.001, attack.t1572
// False Positives:
//   - Legitimate use of Devtunnels will also trigger this.

DeviceNetworkEvents
| where RemoteUrl endswith ".devtunnels.ms"