// Title: Split A File Into Pieces
// Author: Igor Fits, Mikhail Larin, oscd.community
// Date: 2020-10-15
// Level: low
// Description: Detection use of the command "split" to split files into parts and possible transfer.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1030
// False Positives:
//   - Legitimate administrative activity

DeviceProcessEvents
| where FolderPath endswith "/split"