// Title: Cloudflared Portable Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-12-20
// Level: medium
// Description: Detects the execution of the "cloudflared" binary from a non standard location.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090.001
// False Positives:
//   - Legitimate usage of Cloudflared portable versions

DeviceProcessEvents
| where FolderPath endswith "\\cloudflared.exe" and (not((FolderPath contains ":\\Program Files (x86)\\cloudflared\\" or FolderPath contains ":\\Program Files\\cloudflared\\")))