// Title: Gzip Archive Decode Via PowerShell
// Author: Hieu Tran
// Date: 2023-03-13
// Level: medium
// Description: Detects attempts of decoding encoded Gzip archives via PowerShell.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1132.001
// False Positives:
//   - Legitimate administrative scripts may use this functionality. Use "ParentImage" in combination with the script names and allowed users and applications to filter legitimate executions

DeviceProcessEvents
| where ProcessCommandLine contains "GZipStream" and ProcessCommandLine contains "::Decompress"