// Title: HackTool - SharpChisel Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-05
// Level: high
// Description: Detects usage of the Sharp Chisel via the commandline arguments
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090.001
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\SharpChisel.exe" or ProcessVersionInfoProductName =~ "SharpChisel"