// Title: APT PRIVATELOG Image Load Pattern
// Author: Florian Roth (Nextron Systems)
// Date: 2021-09-07
// Level: high
// Description: Detects an image load pattern as seen when a tool named PRIVATELOG is used and rarely observed under legitimate circumstances
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1055, detection.emerging-threats
// False Positives:
//   - Rarely observed

DeviceImageLoadEvents
| where FolderPath endswith "\\clfsw32.dll" and InitiatingProcessFolderPath endswith "\\svchost.exe"