// Title: Potential APT-C-12 BlueMushroom DLL Load Activity Via Regsvr32
// Author: Florian Roth (Nextron Systems), Tim Shelton, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-10-02
// Level: medium
// Description: Detects potential BlueMushroom DLL loading activity via regsvr32 from AppData Local
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.010, detection.emerging-threats

DeviceProcessEvents
| where ProcessCommandLine contains "regsvr32" and ProcessCommandLine contains "\\AppData\\Local\\" and ProcessCommandLine contains ".dll" and ProcessCommandLine contains ",DllEntry"