// Title: Potential Raspberry Robin CPL Execution Activity
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-03-07
// Level: high
// Description: Detects the execution of a ".CPL" file located in the user temp directory via the Shell32 DLL "Control_RunDLL" export function.
// This behavior was observed in multiple Raspberry-Robin variants.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218.011, detection.emerging-threats

DeviceProcessEvents
| where (ProcessCommandLine contains "shell32.dll" and ProcessCommandLine contains "Control_RunDLL" and ProcessCommandLine contains ".CPL") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE") and (InitiatingProcessFolderPath endswith "\\rundll32.exe" or InitiatingProcessFolderPath endswith "\\control.exe") and ProcessCommandLine contains "\\AppData\\Local\\Temp\\"