// Title: Potential Qakbot Rundll32 Execution
// Author: X__Junior (Nextron Systems)
// Date: 2023-05-24
// Level: high
// Description: Detects specific process tree behavior of a "rundll32" execution often linked with potential Qakbot activity.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains ".dll" and ((ProcessCommandLine contains ":\\ProgramData\\" or ProcessCommandLine contains ":\\Users\\Public\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\AppData\\Roaming\\") and FolderPath endswith "\\rundll32.exe" and (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\curl.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe"))