// Title: Potential Devil Bait Related Indicator
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Level: high
// Description: Detects the creation of ".xml" and ".txt" files in folders of the "\AppData\Roaming\Microsoft" directory by uncommon processes. This behavior was seen common across different Devil Bait samples and stages as described by the NCSC
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\schtasks.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe") and FolderPath contains "\\AppData\\Roaming\\Microsoft\\" and (FolderPath endswith ".txt" or FolderPath endswith ".xml")