// Title: UNC4841 - Download Compressed Files From Temp.sh Using Wget
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-16
// Level: high
// Description: Detects execution of "wget" to download a ".zip" or ".rar" files from "temp.sh". As seen used by UNC4841 during their Barracuda ESG zero day exploitation.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1140, detection.emerging-threats

DeviceProcessEvents
| where ProcessCommandLine contains "https://temp.sh/" and (ProcessCommandLine endswith ".rar" or ProcessCommandLine endswith ".zip") and FolderPath endswith "/wget"