// Title: New PortProxy Registry Entry Added
// Author: Andreas Hunkeler (@Karneades)
// Date: 2021-06-22
// Level: medium
// Description: Detects the modification of the PortProxy registry key which is used for port forwarding.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.defense-evasion, attack.command-and-control, attack.t1090
// False Positives:
//   - WSL2 network bridge PowerShell script used for WSL/Kubernetes/Docker (e.g. https://github.com/microsoft/WSL/issues/4150#issuecomment-504209723)
//   - Synergy Software KVM (https://symless.com/synergy)

DeviceRegistryEvents
| where RegistryKey endswith "\\Services\\PortProxy\\v4tov4\\tcp*"