// Title: Path To Screensaver Binary Modified
// Author: Bartlomiej Czyz @bczyz1, oscd.community
// Date: 2020-10-11
// Level: medium
// Description: Detects value modification of registry key containing path to binary used as screensaver.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.002
// False Positives:
//   - Legitimate modification of screensaver

DeviceRegistryEvents
| where RegistryKey endswith "\\Control Panel\\Desktop\\SCRNSAVE.EXE" and (not((InitiatingProcessFolderPath endswith "\\rundll32.exe" or InitiatingProcessFolderPath endswith "\\explorer.exe")))