// Title: Suspicious Process Execution From Fake Recycle.Bin Folder
// Author: X__Junior (Nextron Systems)
// Date: 2023-07-12
// Level: high
// Description: Detects process execution from a fake recycle bin folder, often used to avoid security solution.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath contains "RECYCLERS.BIN\\" or FolderPath contains "RECYCLER.BIN\\"