// Title: User Added To Admin Group Via Dscl
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-03-19
// Level: medium
// Description: Detects attempts to create and add an account to the admin group via "dscl"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.initial-access, attack.privilege-escalation, attack.t1078.003
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains " -append " and ProcessCommandLine contains " /Groups/admin " and ProcessCommandLine contains " GroupMembership ") and FolderPath endswith "/dscl"