// Title: User Added To Admin Group Via Sysadminctl
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-03-19
// Level: medium
// Description: Detects attempts to create and add an account to the admin group via "sysadminctl"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.initial-access, attack.privilege-escalation, attack.t1078.003
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains " -addUser " and ProcessCommandLine contains " -admin ") and FolderPath endswith "/sysadminctl"