// Title: WMI Persistence - Script Event Consumer
// Author: Thomas Patzke
// Date: 2018-03-07
// Level: medium
// Description: Detects WMI script event consumers
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.003
// False Positives:
//   - Legitimate event consumers
//   - Dell computers on some versions register an event consumer that is known to cause false positives when brightness is changed by the corresponding keyboard button

DeviceProcessEvents
| where FolderPath =~ "C:\\WINDOWS\\system32\\wbem\\scrcons.exe" and InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\svchost.exe"