// Title: Forest Blizzard APT - Custom Protocol Handler Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-04-23
// Level: high
// Description: Detects the setting of a custom protocol handler with the name "rogue".
// Seen being created by Forest Blizzard APT as reported by MSFT.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001, detection.emerging-threats
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryValueData =~ "{026CC6D7-34B2-33D5-B551-CA31EB6CE345}" and RegistryKey contains "\\PROTOCOLS\\Handler\\rogue\\CLSID"